SELECT * FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

--SELECT * FROM PORTFOLIOPROJECT..COVIDVACCINATIONS
--ORDER BY 3,4

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM PORTFOLIOPROJECT..COVIDDEATHS
ORDER BY 1,2

-- SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/ TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE LOCATION LIKE '%INDIA%'
ORDER BY 1,2

--  LOOKING AT TOTAL CASES VS POPULATION

SELECT LOCATION, DATE, POPULATION, TOTAL_CASES,  (TOTAL_CASES/ POPULATION)*100 AS COVIDCASESPERCENTAGE
FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE LOCATION LIKE '%INDIA%'
ORDER BY 1,2

-- LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES),  MAX((TOTAL_CASES/ POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM PORTFOLIOPROJECT..COVIDDEATHS
--WHERE LOCATION LIKE '%INDIA%'
GROUP BY LOCATION, POPULATION
ORDER BY  PERCENTPOPULATIONINFECTED DESC


-- SHOWING COUNTRIES WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, POPULATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
--WHERE LOCATION LIKE '%INDIA%'
GROUP BY LOCATION, POPULATION
ORDER BY  TOTALDEATHCOUNT DESC

-- SHOWING THE CONTINENTS WITH THE HIGHEST DEATH COUNT

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
--WHERE LOCATION LIKE '%INDIA%'
GROUP BY CONTINENT
ORDER BY  TOTALDEATHCOUNT DESC

-- GLOBAL NUMBERS

SELECT  SUM( NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, 
(SUM(CAST(NEW_DEATHS AS INT))/  SUM( NEW_CASES))*100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..COVIDDEATHS
--WHERE LOCATION LIKE '%INDIA%'
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- LOOKING AT TOTAL POPULATION VS TOTAL VACCINATIONS

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PORTFOLIOPROJECT..COVIDDEATHS DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
	ON  DEA.LOCATION = VAC.LOCATION AND
		DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3

-- USING CTE ON THE ABOVE TABLE

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED) 
AS (
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PORTFOLIOPROJECT..COVIDDEATHS DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
	ON  DEA.LOCATION = VAC.LOCATION AND
		DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
)
SELECT * , (ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS TOTALPERCANTAGEOFVACCINATEDPEOPLE
FROM POPVSVAC

--CREATING TEMP TABLES

DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED

CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINATED NUMERIC
)

INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM PORTFOLIOPROJECT..COVIDDEATHS DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
	ON  DEA.LOCATION = VAC.LOCATION AND
		DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3
SELECT * , (ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS TOTALPERCANTAGEOFVACCINATEDPEOPLE
FROM #PERCENTPOPULATIONVACCINATED

-- CREATING VIEW TO STORE DATA FOR DATA VISUALIZATIONS
DROP VIEW IF EXISTS DEATHPERCENTAGE

CREATE VIEW DEATHPERCENTAGE AS
SELECT  SUM( NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, 
(SUM(CAST(NEW_DEATHS AS INT))/  SUM( NEW_CASES))*100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..COVIDDEATHS
WHERE CONTINENT IS NOT NULL


